name: test_quadbench
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - openssl
  - ca-certificates
  - zlib
  - xz
  - sqlite
  - tk
  - readline
  - ncurses
  - libffi
  - pip:
      - asttokens==3.0.0
      - casadi==3.6.7
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cvxopt==1.3.2
      - cycler==0.12.1
      - cython==3.0.12
      - decorator==5.1.1
      - executing==2.2.0
      - farama-notifications==0.0.4
      - filelock==3.17.0
      - filterpy==1.4.5
      - flatbuffers==25.2.10
      - fonttools==4.55.8
      - fsspec==2025.2.0
      - future-fstrings==1.2.0
      - gymnasium==0.29.1
      - humanfriendly==10.0
      - iniconfig==2.0.0
      - ipython==8.32.0
      - jedi==0.19.2
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - ml-dtypes==0.5.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - onnxruntime==1.20.1
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.1.0
      - pluggy==1.5.0
      - prompt-toolkit==3.0.50
      - protobuf==5.29.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycryptodomex==3.21.0
      - pygments==2.19.1
      - pyquaternion==0.9.9
      - pytest==8.3.4
      - pytz==2025.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - setuptools-scm==8.1.0
      - stack-data==0.6.3
      - sympy==1.13.1
      - timeout-decorator==0.5.0
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - wcwidth==0.2.13
prefix: /home/dingqi/anaconda3/envs/quadbench
