name: omnidrones_aqb
channels:
  - defaults
dependencies:
  - python=3.10.16
  - pip
  - pip:
      - asttokens
      - casadi
      - cloudpickle
      - coloredlogs
      - contourpy
      - cvxopt
      - cycler
      - cython
      - decorator
      - executing
      - farama-notifications
      - filelock
      - filterpy
      - flatbuffers
      - fonttools
      - fsspec
      - future-fstrings
      - gymnasium==0.29.1
      - humanfriendly
      - iniconfig
      - ipython
      - jedi
      - kiwisolver
      - markupsafe
      - matplotlib
      - matplotlib-inline
      - ml-dtypes
      - networkx
      - onnxruntime
      - opt-einsum
      - pandas
      - parso
      - pexpect
      - pillow
      - pluggy
      - prompt-toolkit
      - protobuf
      - ptyprocess
      - pure-eval
      - pycryptodomex
      - pygments
      - pyquaternion
      - pytest
      - pytz
      - seaborn
      - setuptools-scm
      - stack-data
      - sympy
      - timeout-decorator
      - tqdm
      - traitlets
      - typing-extensions
      - tzdata
      - wcwidth